// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: rates.proto

package rates

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetRatesRequest specifies the calculation method for rate aggregation.
type GetRatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Calculation method: "topN" or "avgNM".
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// Position N (0-based index for topN, start index for avgNM).
	N int32 `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	// End index M for avgNM method (ignored for topN).
	M             int32 `protobuf:"varint,3,opt,name=m,proto3" json:"m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesRequest) Reset() {
	*x = GetRatesRequest{}
	mi := &file_rates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesRequest) ProtoMessage() {}

func (x *GetRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesRequest.ProtoReflect.Descriptor instead.
func (*GetRatesRequest) Descriptor() ([]byte, []int) {
	return file_rates_proto_rawDescGZIP(), []int{0}
}

func (x *GetRatesRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *GetRatesRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *GetRatesRequest) GetM() int32 {
	if x != nil {
		return x.M
	}
	return 0
}

// GetRatesResponse contains calculated USDT rates.
type GetRatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ask price (sell price).
	Ask string `protobuf:"bytes,1,opt,name=ask,proto3" json:"ask,omitempty"`
	// Bid price (buy price).
	Bid string `protobuf:"bytes,2,opt,name=bid,proto3" json:"bid,omitempty"`
	// Timestamp when the rate was fetched.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesResponse) Reset() {
	*x = GetRatesResponse{}
	mi := &file_rates_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesResponse) ProtoMessage() {}

func (x *GetRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rates_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesResponse.ProtoReflect.Descriptor instead.
func (*GetRatesResponse) Descriptor() ([]byte, []int) {
	return file_rates_proto_rawDescGZIP(), []int{1}
}

func (x *GetRatesResponse) GetAsk() string {
	if x != nil {
		return x.Ask
	}
	return ""
}

func (x *GetRatesResponse) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *GetRatesResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_rates_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rates_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_rates_proto_rawDescGZIP(), []int{2}
}

type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service status: "SERVING" or "NOT_SERVING".
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_rates_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rates_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_rates_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_rates_proto protoreflect.FileDescriptor

const file_rates_proto_rawDesc = "" +
	"\n" +
	"\vrates.proto\x12\brates.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n" +
	"\x0fGetRatesRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\f\n" +
	"\x01n\x18\x02 \x01(\x05R\x01n\x12\f\n" +
	"\x01m\x18\x03 \x01(\x05R\x01m\"p\n" +
	"\x10GetRatesResponse\x12\x10\n" +
	"\x03ask\x18\x01 \x01(\tR\x03ask\x12\x10\n" +
	"\x03bid\x18\x02 \x01(\tR\x03bid\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x9d\x01\n" +
	"\fRatesService\x12A\n" +
	"\bGetRates\x12\x19.rates.v1.GetRatesRequest\x1a\x1a.rates.v1.GetRatesResponse\x12J\n" +
	"\vHealthCheck\x12\x1c.rates.v1.HealthCheckRequest\x1a\x1d.rates.v1.HealthCheckResponseB\x1cZ\x1ausdt-rates/api/proto/ratesb\x06proto3"

var (
	file_rates_proto_rawDescOnce sync.Once
	file_rates_proto_rawDescData []byte
)

func file_rates_proto_rawDescGZIP() []byte {
	file_rates_proto_rawDescOnce.Do(func() {
		file_rates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rates_proto_rawDesc), len(file_rates_proto_rawDesc)))
	})
	return file_rates_proto_rawDescData
}

var file_rates_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rates_proto_goTypes = []any{
	(*GetRatesRequest)(nil),       // 0: rates.v1.GetRatesRequest
	(*GetRatesResponse)(nil),      // 1: rates.v1.GetRatesResponse
	(*HealthCheckRequest)(nil),    // 2: rates.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 3: rates.v1.HealthCheckResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_rates_proto_depIdxs = []int32{
	4, // 0: rates.v1.GetRatesResponse.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: rates.v1.RatesService.GetRates:input_type -> rates.v1.GetRatesRequest
	2, // 2: rates.v1.RatesService.HealthCheck:input_type -> rates.v1.HealthCheckRequest
	1, // 3: rates.v1.RatesService.GetRates:output_type -> rates.v1.GetRatesResponse
	3, // 4: rates.v1.RatesService.HealthCheck:output_type -> rates.v1.HealthCheckResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rates_proto_init() }
func file_rates_proto_init() {
	if File_rates_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rates_proto_rawDesc), len(file_rates_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rates_proto_goTypes,
		DependencyIndexes: file_rates_proto_depIdxs,
		MessageInfos:      file_rates_proto_msgTypes,
	}.Build()
	File_rates_proto = out.File
	file_rates_proto_goTypes = nil
	file_rates_proto_depIdxs = nil
}
